//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace ThirdStoreBusiness.API.Neto
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "NetoAPI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "NetoAPI", IsNullable = false)]
    public partial class GetOrderResponse
    {

        private GetOrderResponseOrder[] orderField;

        private string currentTimeField;

        private GetOrderResponseAck ackField;

        private GetOrderResponseMessages messagesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Order", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetOrderResponseOrder[] Order
        {
            get
            {
                return this.orderField;
            }
            set
            {
                this.orderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CurrentTime
        {
            get
            {
                return this.currentTimeField;
            }
            set
            {
                this.currentTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetOrderResponseAck Ack
        {
            get
            {
                return this.ackField;
            }
            set
            {
                this.ackField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetOrderResponseMessages Messages
        {
            get
            {
                return this.messagesField;
            }
            set
            {
                this.messagesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "NetoAPI")]
    public partial class GetOrderResponseOrder
    {

        private GetOrderResponseOrderOrderLine[] orderLineField;

        private string orderIDField;

        private string idField;

        private string componentOfKitField;

        private string kitPartIDField;

        private string shippingOptionField;

        private string deliveryInstructionField;

        private string relatedOrderIDField;

        private string grandTotalField;

        private bool taxInclusiveField;

        private bool taxInclusiveFieldSpecified;

        private decimal orderTaxField;

        private bool orderTaxFieldSpecified;

        private decimal surchargeTotalField;

        private bool surchargeTotalFieldSpecified;

        private decimal surchargeTaxableField;

        private bool surchargeTaxableFieldSpecified;

        private decimal shippingTotalField;

        private bool shippingTotalFieldSpecified;

        private decimal shippingTaxField;

        private bool shippingTaxFieldSpecified;

        private decimal shippingDiscountField;

        private bool shippingDiscountFieldSpecified;

        private System.DateTime dateRequiredField;

        private bool dateRequiredFieldSpecified;

        private System.DateTime? dateInvoicedField;

        private bool dateInvoicedFieldSpecified;

        private System.DateTime? datePaidField;

        private bool datePaidFieldSpecified;

        private System.DateTime datePlacedField;

        private bool datePlacedFieldSpecified;

        private System.DateTime dateUpdatedField;

        private bool dateUpdatedFieldSpecified;

        private bool shippingSignatureField;

        private bool shippingSignatureFieldSpecified;

        private string realtimeConfirmationField;

        private string internalOrderNotesField;

        private string usernameField;

        private string orderStatusField;

        private string orderTypeField;

        private string onHoldTypeField;

        private string emailField;

        private string salesPersonField;

        private string customerRef1Field;

        private string customerRef2Field;

        private string customerRef3Field;

        private string customerRef4Field;

        private string customerRef5Field;

        private string customerRef6Field;

        private string customerRef7Field;

        private string customerRef8Field;

        private string customerRef9Field;

        private string customerRef10Field;

        private string salesChannelField;

        private string shipFirstNameField;

        private string shipLastNameField;

        private string shipCompanyField;

        private string shipStreetLine1Field;

        private string shipStreetLine2Field;

        private string shipCityField;

        private string shipCountryField;

        private string shipStateField;

        private string shipPostCodeField;

        private string shipPhoneField;

        private string shipFaxField;

        private string billFirstNameField;

        private string billLastNameField;

        private string billCompanyField;

        private string billStreetLine1Field;

        private string billStreetLine2Field;

        private string billCityField;

        private string billCountryField;

        private string billStateField;

        private string billPostCodeField;

        private string billPhoneField;

        private string billFaxField;

        private decimal productSubtotalField;

        private bool productSubtotalFieldSpecified;

        private string purchaseOrderNumberField;

        private string couponCodeField;

        private decimal couponDiscountField;

        private bool couponDiscountFieldSpecified;

        private string completeStatusField;

        private GetOrderResponseOrderEBay eBayField;

        private GetOrderResponseOrderOrderPayment[] orderPaymentField;

        private GetOrderResponseOrderStickyNotes[] stickyNotesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrderLine", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetOrderResponseOrderOrderLine[] OrderLine
        {
            get
            {
                return this.orderLineField;
            }
            set
            {
                this.orderLineField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderID
        {
            get
            {
                return this.orderIDField;
            }
            set
            {
                this.orderIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ComponentOfKit
        {
            get
            {
                return this.componentOfKitField;
            }
            set
            {
                this.componentOfKitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KitPartID
        {
            get
            {
                return this.kitPartIDField;
            }
            set
            {
                this.kitPartIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShippingOption
        {
            get
            {
                return this.shippingOptionField;
            }
            set
            {
                this.shippingOptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DeliveryInstruction
        {
            get
            {
                return this.deliveryInstructionField;
            }
            set
            {
                this.deliveryInstructionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RelatedOrderID
        {
            get
            {
                return this.relatedOrderIDField;
            }
            set
            {
                this.relatedOrderIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GrandTotal
        {
            get
            {
                return this.grandTotalField;
            }
            set
            {
                this.grandTotalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool TaxInclusive
        {
            get
            {
                return this.taxInclusiveField;
            }
            set
            {
                this.taxInclusiveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TaxInclusiveSpecified
        {
            get
            {
                return this.taxInclusiveFieldSpecified;
            }
            set
            {
                this.taxInclusiveFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal OrderTax
        {
            get
            {
                return this.orderTaxField;
            }
            set
            {
                this.orderTaxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderTaxSpecified
        {
            get
            {
                return this.orderTaxFieldSpecified;
            }
            set
            {
                this.orderTaxFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SurchargeTotal
        {
            get
            {
                return this.surchargeTotalField;
            }
            set
            {
                this.surchargeTotalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SurchargeTotalSpecified
        {
            get
            {
                return this.surchargeTotalFieldSpecified;
            }
            set
            {
                this.surchargeTotalFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SurchargeTaxable
        {
            get
            {
                return this.surchargeTaxableField;
            }
            set
            {
                this.surchargeTaxableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SurchargeTaxableSpecified
        {
            get
            {
                return this.surchargeTaxableFieldSpecified;
            }
            set
            {
                this.surchargeTaxableFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ShippingTotal
        {
            get
            {
                return this.shippingTotalField;
            }
            set
            {
                this.shippingTotalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShippingTotalSpecified
        {
            get
            {
                return this.shippingTotalFieldSpecified;
            }
            set
            {
                this.shippingTotalFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ShippingTax
        {
            get
            {
                return this.shippingTaxField;
            }
            set
            {
                this.shippingTaxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShippingTaxSpecified
        {
            get
            {
                return this.shippingTaxFieldSpecified;
            }
            set
            {
                this.shippingTaxFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ShippingDiscount
        {
            get
            {
                return this.shippingDiscountField;
            }
            set
            {
                this.shippingDiscountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShippingDiscountSpecified
        {
            get
            {
                return this.shippingDiscountFieldSpecified;
            }
            set
            {
                this.shippingDiscountFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DateRequired
        {
            get
            {
                return this.dateRequiredField;
            }
            set
            {
                this.dateRequiredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateRequiredSpecified
        {
            get
            {
                return this.dateRequiredFieldSpecified;
            }
            set
            {
                this.dateRequiredFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
        public System.DateTime? DateInvoiced
        {
            get
            {
                return this.dateInvoicedField;
            }
            set
            {
                this.dateInvoicedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateInvoicedSpecified
        {
            get
            {
                return this.dateInvoicedFieldSpecified;
            }
            set
            {
                this.dateInvoicedFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime? DatePaid
        {
            get
            {
                return this.datePaidField;
            }
            set
            {
                this.datePaidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DatePaidSpecified
        {
            get
            {
                return this.datePaidFieldSpecified;
            }
            set
            {
                this.datePaidFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DatePlaced
        {
            get
            {
                return this.datePlacedField;
            }
            set
            {
                this.datePlacedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DatePlacedSpecified
        {
            get
            {
                return this.datePlacedFieldSpecified;
            }
            set
            {
                this.datePlacedFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DateUpdated
        {
            get
            {
                return this.dateUpdatedField;
            }
            set
            {
                this.dateUpdatedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateUpdatedSpecified
        {
            get
            {
                return this.dateUpdatedFieldSpecified;
            }
            set
            {
                this.dateUpdatedFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool ShippingSignature
        {
            get
            {
                return this.shippingSignatureField;
            }
            set
            {
                this.shippingSignatureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShippingSignatureSpecified
        {
            get
            {
                return this.shippingSignatureFieldSpecified;
            }
            set
            {
                this.shippingSignatureFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RealtimeConfirmation
        {
            get
            {
                return this.realtimeConfirmationField;
            }
            set
            {
                this.realtimeConfirmationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InternalOrderNotes
        {
            get
            {
                return this.internalOrderNotesField;
            }
            set
            {
                this.internalOrderNotesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderStatus
        {
            get
            {
                return this.orderStatusField;
            }
            set
            {
                this.orderStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderType
        {
            get
            {
                return this.orderTypeField;
            }
            set
            {
                this.orderTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OnHoldType
        {
            get
            {
                return this.onHoldTypeField;
            }
            set
            {
                this.onHoldTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SalesPerson
        {
            get
            {
                return this.salesPersonField;
            }
            set
            {
                this.salesPersonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerRef1
        {
            get
            {
                return this.customerRef1Field;
            }
            set
            {
                this.customerRef1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerRef2
        {
            get
            {
                return this.customerRef2Field;
            }
            set
            {
                this.customerRef2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerRef3
        {
            get
            {
                return this.customerRef3Field;
            }
            set
            {
                this.customerRef3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerRef4
        {
            get
            {
                return this.customerRef4Field;
            }
            set
            {
                this.customerRef4Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerRef5
        {
            get
            {
                return this.customerRef5Field;
            }
            set
            {
                this.customerRef5Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerRef6
        {
            get
            {
                return this.customerRef6Field;
            }
            set
            {
                this.customerRef6Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerRef7
        {
            get
            {
                return this.customerRef7Field;
            }
            set
            {
                this.customerRef7Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerRef8
        {
            get
            {
                return this.customerRef8Field;
            }
            set
            {
                this.customerRef8Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerRef9
        {
            get
            {
                return this.customerRef9Field;
            }
            set
            {
                this.customerRef9Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerRef10
        {
            get
            {
                return this.customerRef10Field;
            }
            set
            {
                this.customerRef10Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SalesChannel
        {
            get
            {
                return this.salesChannelField;
            }
            set
            {
                this.salesChannelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipFirstName
        {
            get
            {
                return this.shipFirstNameField;
            }
            set
            {
                this.shipFirstNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipLastName
        {
            get
            {
                return this.shipLastNameField;
            }
            set
            {
                this.shipLastNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipCompany
        {
            get
            {
                return this.shipCompanyField;
            }
            set
            {
                this.shipCompanyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipStreetLine1
        {
            get
            {
                return this.shipStreetLine1Field;
            }
            set
            {
                this.shipStreetLine1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipStreetLine2
        {
            get
            {
                return this.shipStreetLine2Field;
            }
            set
            {
                this.shipStreetLine2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipCity
        {
            get
            {
                return this.shipCityField;
            }
            set
            {
                this.shipCityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipCountry
        {
            get
            {
                return this.shipCountryField;
            }
            set
            {
                this.shipCountryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipState
        {
            get
            {
                return this.shipStateField;
            }
            set
            {
                this.shipStateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipPostCode
        {
            get
            {
                return this.shipPostCodeField;
            }
            set
            {
                this.shipPostCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipPhone
        {
            get
            {
                return this.shipPhoneField;
            }
            set
            {
                this.shipPhoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipFax
        {
            get
            {
                return this.shipFaxField;
            }
            set
            {
                this.shipFaxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BillFirstName
        {
            get
            {
                return this.billFirstNameField;
            }
            set
            {
                this.billFirstNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BillLastName
        {
            get
            {
                return this.billLastNameField;
            }
            set
            {
                this.billLastNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BillCompany
        {
            get
            {
                return this.billCompanyField;
            }
            set
            {
                this.billCompanyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BillStreetLine1
        {
            get
            {
                return this.billStreetLine1Field;
            }
            set
            {
                this.billStreetLine1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BillStreetLine2
        {
            get
            {
                return this.billStreetLine2Field;
            }
            set
            {
                this.billStreetLine2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BillCity
        {
            get
            {
                return this.billCityField;
            }
            set
            {
                this.billCityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BillCountry
        {
            get
            {
                return this.billCountryField;
            }
            set
            {
                this.billCountryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BillState
        {
            get
            {
                return this.billStateField;
            }
            set
            {
                this.billStateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BillPostCode
        {
            get
            {
                return this.billPostCodeField;
            }
            set
            {
                this.billPostCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BillPhone
        {
            get
            {
                return this.billPhoneField;
            }
            set
            {
                this.billPhoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BillFax
        {
            get
            {
                return this.billFaxField;
            }
            set
            {
                this.billFaxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ProductSubtotal
        {
            get
            {
                return this.productSubtotalField;
            }
            set
            {
                this.productSubtotalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProductSubtotalSpecified
        {
            get
            {
                return this.productSubtotalFieldSpecified;
            }
            set
            {
                this.productSubtotalFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PurchaseOrderNumber
        {
            get
            {
                return this.purchaseOrderNumberField;
            }
            set
            {
                this.purchaseOrderNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CouponCode
        {
            get
            {
                return this.couponCodeField;
            }
            set
            {
                this.couponCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal CouponDiscount
        {
            get
            {
                return this.couponDiscountField;
            }
            set
            {
                this.couponDiscountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CouponDiscountSpecified
        {
            get
            {
                return this.couponDiscountFieldSpecified;
            }
            set
            {
                this.couponDiscountFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CompleteStatus
        {
            get
            {
                return this.completeStatusField;
            }
            set
            {
                this.completeStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetOrderResponseOrderEBay eBay
        {
            get
            {
                return this.eBayField;
            }
            set
            {
                this.eBayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrderPayment", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetOrderResponseOrderOrderPayment[] OrderPayment
        {
            get
            {
                return this.orderPaymentField;
            }
            set
            {
                this.orderPaymentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StickyNotes", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetOrderResponseOrderStickyNotes[] StickyNotes
        {
            get
            {
                return this.stickyNotesField;
            }
            set
            {
                this.stickyNotesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "NetoAPI")]
    public partial class GetOrderResponseOrderOrderLine
    {

        private string quantityField;

        private string sKUField;

        private string orderLineIDField;

        private string productNameField;

        private string itemNotesField;

        private string serialNumberField;

        private string pickQuantityField;

        private string backorderQuantityField;

        private decimal unitPriceField;

        private bool unitPriceFieldSpecified;

        private decimal taxField;

        private bool taxFieldSpecified;

        private string taxCodeField;

        private string warehouseIDField;

        private string warehouseNameField;

        private string warehouseReferenceField;

        private decimal percentDiscountField;

        private bool percentDiscountFieldSpecified;

        private decimal productDiscountField;

        private bool productDiscountFieldSpecified;

        private decimal costPriceField;

        private bool costPriceFieldSpecified;

        private string shippingMethodField;

        private string shippingTrackingField;

        private decimal shippingField;

        private bool shippingFieldSpecified;

        private decimal weightField;

        private bool weightFieldSpecified;

        private decimal cubicField;

        private bool cubicFieldSpecified;

        private string extraField;

        private GetOrderResponseOrderOrderLineExtraOption[] extraOptionsField;

        private string binLocField;

        private string quantityShippedField;

        private decimal couponDiscountField;

        private bool couponDiscountFieldSpecified;

        private GetOrderResponseOrderOrderLineEBay eBayField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        public string Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SKU
        {
            get
            {
                return this.sKUField;
            }
            set
            {
                this.sKUField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderLineID
        {
            get
            {
                return this.orderLineIDField;
            }
            set
            {
                this.orderLineIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProductName
        {
            get
            {
                return this.productNameField;
            }
            set
            {
                this.productNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ItemNotes
        {
            get
            {
                return this.itemNotesField;
            }
            set
            {
                this.itemNotesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SerialNumber
        {
            get
            {
                return this.serialNumberField;
            }
            set
            {
                this.serialNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        public string PickQuantity
        {
            get
            {
                return this.pickQuantityField;
            }
            set
            {
                this.pickQuantityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        public string BackorderQuantity
        {
            get
            {
                return this.backorderQuantityField;
            }
            set
            {
                this.backorderQuantityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal UnitPrice
        {
            get
            {
                return this.unitPriceField;
            }
            set
            {
                this.unitPriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UnitPriceSpecified
        {
            get
            {
                return this.unitPriceFieldSpecified;
            }
            set
            {
                this.unitPriceFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Tax
        {
            get
            {
                return this.taxField;
            }
            set
            {
                this.taxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TaxSpecified
        {
            get
            {
                return this.taxFieldSpecified;
            }
            set
            {
                this.taxFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TaxCode
        {
            get
            {
                return this.taxCodeField;
            }
            set
            {
                this.taxCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        public string WarehouseID
        {
            get
            {
                return this.warehouseIDField;
            }
            set
            {
                this.warehouseIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WarehouseName
        {
            get
            {
                return this.warehouseNameField;
            }
            set
            {
                this.warehouseNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WarehouseReference
        {
            get
            {
                return this.warehouseReferenceField;
            }
            set
            {
                this.warehouseReferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal PercentDiscount
        {
            get
            {
                return this.percentDiscountField;
            }
            set
            {
                this.percentDiscountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PercentDiscountSpecified
        {
            get
            {
                return this.percentDiscountFieldSpecified;
            }
            set
            {
                this.percentDiscountFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ProductDiscount
        {
            get
            {
                return this.productDiscountField;
            }
            set
            {
                this.productDiscountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProductDiscountSpecified
        {
            get
            {
                return this.productDiscountFieldSpecified;
            }
            set
            {
                this.productDiscountFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal CostPrice
        {
            get
            {
                return this.costPriceField;
            }
            set
            {
                this.costPriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CostPriceSpecified
        {
            get
            {
                return this.costPriceFieldSpecified;
            }
            set
            {
                this.costPriceFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShippingMethod
        {
            get
            {
                return this.shippingMethodField;
            }
            set
            {
                this.shippingMethodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShippingTracking
        {
            get
            {
                return this.shippingTrackingField;
            }
            set
            {
                this.shippingTrackingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Shipping
        {
            get
            {
                return this.shippingField;
            }
            set
            {
                this.shippingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShippingSpecified
        {
            get
            {
                return this.shippingFieldSpecified;
            }
            set
            {
                this.shippingFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Weight
        {
            get
            {
                return this.weightField;
            }
            set
            {
                this.weightField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WeightSpecified
        {
            get
            {
                return this.weightFieldSpecified;
            }
            set
            {
                this.weightFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Cubic
        {
            get
            {
                return this.cubicField;
            }
            set
            {
                this.cubicField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CubicSpecified
        {
            get
            {
                return this.cubicFieldSpecified;
            }
            set
            {
                this.cubicFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Extra
        {
            get
            {
                return this.extraField;
            }
            set
            {
                this.extraField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ExtraOption", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public GetOrderResponseOrderOrderLineExtraOption[] ExtraOptions
        {
            get
            {
                return this.extraOptionsField;
            }
            set
            {
                this.extraOptionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BinLoc
        {
            get
            {
                return this.binLocField;
            }
            set
            {
                this.binLocField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        public string QuantityShipped
        {
            get
            {
                return this.quantityShippedField;
            }
            set
            {
                this.quantityShippedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal CouponDiscount
        {
            get
            {
                return this.couponDiscountField;
            }
            set
            {
                this.couponDiscountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CouponDiscountSpecified
        {
            get
            {
                return this.couponDiscountFieldSpecified;
            }
            set
            {
                this.couponDiscountFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetOrderResponseOrderOrderLineEBay eBay
        {
            get
            {
                return this.eBayField;
            }
            set
            {
                this.eBayField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "NetoAPI")]
    public partial class GetOrderResponseOrderOrderLineExtraOption
    {

        private string nameField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "NetoAPI")]
    public partial class GetOrderResponseOrderOrderLineEBay
    {

        private string eBayUsernameField;

        private string eBayStoreNameField;

        private string eBayAuctionIDField;

        private string eBayTransactionIDField;

        private string listingTypeField;

        private System.DateTime dateCreatedField;

        private bool dateCreatedFieldSpecified;

        private System.DateTime? datePaidField;

        private bool datePaidFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string eBayUsername
        {
            get
            {
                return this.eBayUsernameField;
            }
            set
            {
                this.eBayUsernameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string eBayStoreName
        {
            get
            {
                return this.eBayStoreNameField;
            }
            set
            {
                this.eBayStoreNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string eBayAuctionID
        {
            get
            {
                return this.eBayAuctionIDField;
            }
            set
            {
                this.eBayAuctionIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string eBayTransactionID
        {
            get
            {
                return this.eBayTransactionIDField;
            }
            set
            {
                this.eBayTransactionIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ListingType
        {
            get
            {
                return this.listingTypeField;
            }
            set
            {
                this.listingTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
        public System.DateTime DateCreated
        {
            get
            {
                return this.dateCreatedField;
            }
            set
            {
                this.dateCreatedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateCreatedSpecified
        {
            get
            {
                return this.dateCreatedFieldSpecified;
            }
            set
            {
                this.dateCreatedFieldSpecified = value;
            }
        }

        ///// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
        //public System.DateTime? DatePaid
        //{
        //    get
        //    {
        //        return this.datePaidField;
        //    }
        //    set
        //    {
        //        this.datePaidField = value;
        //    }
        //}

        ///// <remarks/>
        //[System.Xml.Serialization.XmlIgnoreAttribute()]
        //public bool DatePaidSpecified
        //{
        //    get
        //    {
        //        return this.datePaidFieldSpecified;
        //    }
        //    set
        //    {
        //        this.datePaidFieldSpecified = value;
        //    }
        //}
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "NetoAPI")]
    public partial class GetOrderResponseOrderEBay
    {

        private string eBayUsernameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string eBayUsername
        {
            get
            {
                return this.eBayUsernameField;
            }
            set
            {
                this.eBayUsernameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "NetoAPI")]
    public partial class GetOrderResponseOrderOrderPayment
    {

        private string orderPaymentIdField;

        private decimal orderPaymentAmountField;

        private bool orderPaymentAmountFieldSpecified;

        private string paymentTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderPaymentId
        {
            get
            {
                return this.orderPaymentIdField;
            }
            set
            {
                this.orderPaymentIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal OrderPaymentAmount
        {
            get
            {
                return this.orderPaymentAmountField;
            }
            set
            {
                this.orderPaymentAmountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderPaymentAmountSpecified
        {
            get
            {
                return this.orderPaymentAmountFieldSpecified;
            }
            set
            {
                this.orderPaymentAmountFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PaymentType
        {
            get
            {
                return this.paymentTypeField;
            }
            set
            {
                this.paymentTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "NetoAPI")]
    public partial class GetOrderResponseOrderStickyNotes
    {

        private string stickyNoteIDField;

        private string titleField;

        private string descriptionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        public string StickyNoteID
        {
            get
            {
                return this.stickyNoteIDField;
            }
            set
            {
                this.stickyNoteIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "NetoAPI")]
    public enum GetOrderResponseAck
    {

        /// <remarks/>
        Error,

        /// <remarks/>
        Warning,

        /// <remarks/>
        Success,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "NetoAPI")]
    public partial class GetOrderResponseMessages
    {

        private GetOrderResponseMessagesError[] errorField;

        private GetOrderResponseMessagesWarning[] warningField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Error", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetOrderResponseMessagesError[] Error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Warning", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetOrderResponseMessagesWarning[] Warning
        {
            get
            {
                return this.warningField;
            }
            set
            {
                this.warningField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "NetoAPI")]
    public partial class GetOrderResponseMessagesError
    {

        private string messageField;

        private string severityCodeField;

        private string descriptionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SeverityCode
        {
            get
            {
                return this.severityCodeField;
            }
            set
            {
                this.severityCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "NetoAPI")]
    public partial class GetOrderResponseMessagesWarning
    {

        private string messageField;

        private string severityCodeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SeverityCode
        {
            get
            {
                return this.severityCodeField;
            }
            set
            {
                this.severityCodeField = value;
            }
        }
    }
}