//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace ThirdStoreBusiness.API.Neto
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "NetoAPI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "NetoAPI", IsNullable = false)]
    public partial class GetOrder
    {

        private GetOrderFilter filterField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetOrderFilter Filter
        {
            get
            {
                return this.filterField;
            }
            set
            {
                this.filterField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "NetoAPI")]
    public partial class GetOrderFilter
    {

        private string[] orderIDField;

        private string[] usernameField;

        private string[] sKUField;

        private string[] supplierField;

        private GetOrderFilterOrderStatus[] orderStatusField;

        private GetOrderFilterOrderType[] orderTypeField;

        private GetOrderFilterOnHoldType[] onHoldTypeField;

        private GetOrderFilterCompleteStatus[] completeStatusField;

        private GetOrderFilterPaymentStatus[] paymentStatusField;

        private GetOrderFilterExportStatus[] exportStatusField;

        private string[] warehouseIDField;

        private GetOrderFilterExportedToWMS[] exportedToWMSField;

        private string[] shippingMethodField;

        private string[] salesChannelField;

        private System.DateTime datePaidFromField;

        private bool datePaidFromFieldSpecified;

        private System.DateTime datePaidToField;

        private bool datePaidToFieldSpecified;

        private System.DateTime dateRequiredFromField;

        private bool dateRequiredFromFieldSpecified;

        private System.DateTime dateRequiredToField;

        private bool dateRequiredToFieldSpecified;

        private System.DateTime dateInvoicedFromField;

        private bool dateInvoicedFromFieldSpecified;

        private System.DateTime dateInvoicedToField;

        private bool dateInvoicedToFieldSpecified;

        private System.DateTime datePlacedFromField;

        private System.DateTime datePlacedToField;

        private System.DateTime dateUpdatedFromField;

        private bool dateUpdatedFromFieldSpecified;

        private System.DateTime dateUpdatedToField;

        private bool dateUpdatedToFieldSpecified;

        private System.DateTime dateCompletedFromField;

        private bool dateCompletedFromFieldSpecified;

        private System.DateTime dateCompletedToField;

        private bool dateCompletedToFieldSpecified;

        private System.DateTime warehouseQuantityUpdatedFromField;

        private bool warehouseQuantityUpdatedFromFieldSpecified;

        private System.DateTime warehouseQuantityUpdatedToField;

        private bool warehouseQuantityUpdatedToFieldSpecified;

        private GetOrderFilterSplitKitComponents splitKitComponentsField;

        private bool splitKitComponentsFieldSpecified;

        private string pageField;

        private string limitField;

        private GetOrderFilterOutputSelector[] outputSelectorField;

        private GetOrderFilterUpdateResults updateResultsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrderID", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] OrderID
        {
            get
            {
                return this.orderIDField;
            }
            set
            {
                this.orderIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Username", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SKU", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] SKU
        {
            get
            {
                return this.sKUField;
            }
            set
            {
                this.sKUField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Supplier", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] Supplier
        {
            get
            {
                return this.supplierField;
            }
            set
            {
                this.supplierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrderStatus", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetOrderFilterOrderStatus[] OrderStatus
        {
            get
            {
                return this.orderStatusField;
            }
            set
            {
                this.orderStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrderType", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetOrderFilterOrderType[] OrderType
        {
            get
            {
                return this.orderTypeField;
            }
            set
            {
                this.orderTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OnHoldType", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetOrderFilterOnHoldType[] OnHoldType
        {
            get
            {
                return this.onHoldTypeField;
            }
            set
            {
                this.onHoldTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CompleteStatus", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetOrderFilterCompleteStatus[] CompleteStatus
        {
            get
            {
                return this.completeStatusField;
            }
            set
            {
                this.completeStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PaymentStatus", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetOrderFilterPaymentStatus[] PaymentStatus
        {
            get
            {
                return this.paymentStatusField;
            }
            set
            {
                this.paymentStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExportStatus", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetOrderFilterExportStatus[] ExportStatus
        {
            get
            {
                return this.exportStatusField;
            }
            set
            {
                this.exportStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WarehouseID", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        public string[] WarehouseID
        {
            get
            {
                return this.warehouseIDField;
            }
            set
            {
                this.warehouseIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExportedToWMS", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetOrderFilterExportedToWMS[] ExportedToWMS
        {
            get
            {
                return this.exportedToWMSField;
            }
            set
            {
                this.exportedToWMSField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShippingMethod", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] ShippingMethod
        {
            get
            {
                return this.shippingMethodField;
            }
            set
            {
                this.shippingMethodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesChannel", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] SalesChannel
        {
            get
            {
                return this.salesChannelField;
            }
            set
            {
                this.salesChannelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DatePaidFrom
        {
            get
            {
                return this.datePaidFromField;
            }
            set
            {
                this.datePaidFromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DatePaidFromSpecified
        {
            get
            {
                return this.datePaidFromFieldSpecified;
            }
            set
            {
                this.datePaidFromFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DatePaidTo
        {
            get
            {
                return this.datePaidToField;
            }
            set
            {
                this.datePaidToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DatePaidToSpecified
        {
            get
            {
                return this.datePaidToFieldSpecified;
            }
            set
            {
                this.datePaidToFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DateRequiredFrom
        {
            get
            {
                return this.dateRequiredFromField;
            }
            set
            {
                this.dateRequiredFromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateRequiredFromSpecified
        {
            get
            {
                return this.dateRequiredFromFieldSpecified;
            }
            set
            {
                this.dateRequiredFromFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DateRequiredTo
        {
            get
            {
                return this.dateRequiredToField;
            }
            set
            {
                this.dateRequiredToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateRequiredToSpecified
        {
            get
            {
                return this.dateRequiredToFieldSpecified;
            }
            set
            {
                this.dateRequiredToFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DateInvoicedFrom
        {
            get
            {
                return this.dateInvoicedFromField;
            }
            set
            {
                this.dateInvoicedFromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateInvoicedFromSpecified
        {
            get
            {
                return this.dateInvoicedFromFieldSpecified;
            }
            set
            {
                this.dateInvoicedFromFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DateInvoicedTo
        {
            get
            {
                return this.dateInvoicedToField;
            }
            set
            {
                this.dateInvoicedToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateInvoicedToSpecified
        {
            get
            {
                return this.dateInvoicedToFieldSpecified;
            }
            set
            {
                this.dateInvoicedToFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DatePlacedFrom
        {
            get
            {
                return this.datePlacedFromField;
            }
            set
            {
                this.datePlacedFromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DatePlacedTo
        {
            get
            {
                return this.datePlacedToField;
            }
            set
            {
                this.datePlacedToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DateUpdatedFrom
        {
            get
            {
                return this.dateUpdatedFromField;
            }
            set
            {
                this.dateUpdatedFromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateUpdatedFromSpecified
        {
            get
            {
                return this.dateUpdatedFromFieldSpecified;
            }
            set
            {
                this.dateUpdatedFromFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DateUpdatedTo
        {
            get
            {
                return this.dateUpdatedToField;
            }
            set
            {
                this.dateUpdatedToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateUpdatedToSpecified
        {
            get
            {
                return this.dateUpdatedToFieldSpecified;
            }
            set
            {
                this.dateUpdatedToFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DateCompletedFrom
        {
            get
            {
                return this.dateCompletedFromField;
            }
            set
            {
                this.dateCompletedFromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateCompletedFromSpecified
        {
            get
            {
                return this.dateCompletedFromFieldSpecified;
            }
            set
            {
                this.dateCompletedFromFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DateCompletedTo
        {
            get
            {
                return this.dateCompletedToField;
            }
            set
            {
                this.dateCompletedToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateCompletedToSpecified
        {
            get
            {
                return this.dateCompletedToFieldSpecified;
            }
            set
            {
                this.dateCompletedToFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime WarehouseQuantityUpdatedFrom
        {
            get
            {
                return this.warehouseQuantityUpdatedFromField;
            }
            set
            {
                this.warehouseQuantityUpdatedFromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WarehouseQuantityUpdatedFromSpecified
        {
            get
            {
                return this.warehouseQuantityUpdatedFromFieldSpecified;
            }
            set
            {
                this.warehouseQuantityUpdatedFromFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime WarehouseQuantityUpdatedTo
        {
            get
            {
                return this.warehouseQuantityUpdatedToField;
            }
            set
            {
                this.warehouseQuantityUpdatedToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WarehouseQuantityUpdatedToSpecified
        {
            get
            {
                return this.warehouseQuantityUpdatedToFieldSpecified;
            }
            set
            {
                this.warehouseQuantityUpdatedToFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetOrderFilterSplitKitComponents SplitKitComponents
        {
            get
            {
                return this.splitKitComponentsField;
            }
            set
            {
                this.splitKitComponentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SplitKitComponentsSpecified
        {
            get
            {
                return this.splitKitComponentsFieldSpecified;
            }
            set
            {
                this.splitKitComponentsFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        public string Page
        {
            get
            {
                return this.pageField;
            }
            set
            {
                this.pageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        public string Limit
        {
            get
            {
                return this.limitField;
            }
            set
            {
                this.limitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OutputSelector", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetOrderFilterOutputSelector[] OutputSelector
        {
            get
            {
                return this.outputSelectorField;
            }
            set
            {
                this.outputSelectorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetOrderFilterUpdateResults UpdateResults
        {
            get
            {
                return this.updateResultsField;
            }
            set
            {
                this.updateResultsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "NetoAPI")]
    public enum GetOrderFilterOrderStatus
    {

        /// <remarks/>
        New,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("New Backorder")]
        NewBackorder,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Backorder Approved")]
        BackorderApproved,

        /// <remarks/>
        Pick,

        /// <remarks/>
        Pack,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Pending Pickup")]
        PendingPickup,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Pending Dispatch")]
        PendingDispatch,

        /// <remarks/>
        Dispatched,

        /// <remarks/>
        Cancelled,

        /// <remarks/>
        Uncommitted,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("On Hold")]
        OnHold,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "NetoAPI")]
    public enum GetOrderFilterOrderType
    {

        /// <remarks/>
        sales,

        /// <remarks/>
        dropshipping,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "NetoAPI")]
    public enum GetOrderFilterOnHoldType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("On Hold")]
        OnHold,

        /// <remarks/>
        Layby,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "NetoAPI")]
    public enum GetOrderFilterCompleteStatus
    {

        /// <remarks/>
        Approved,

        /// <remarks/>
        Incomplete,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "NetoAPI")]
    public enum GetOrderFilterPaymentStatus
    {

        /// <remarks/>
        FullyPaid,

        /// <remarks/>
        PartialPaid,

        /// <remarks/>
        Pending,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "NetoAPI")]
    public enum GetOrderFilterExportStatus
    {

        /// <remarks/>
        Pending,

        /// <remarks/>
        Exported,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "NetoAPI")]
    public enum GetOrderFilterExportedToWMS
    {

        /// <remarks/>
        True,

        /// <remarks/>
        False,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "NetoAPI")]
    public enum GetOrderFilterSplitKitComponents
    {

        /// <remarks/>
        True,

        /// <remarks/>
        False,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "NetoAPI")]
    public enum GetOrderFilterOutputSelector
    {

        /// <remarks/>
        ID,

        /// <remarks/>
        ShippingOption,

        /// <remarks/>
        DeliveryInstruction,

        /// <remarks/>
        RelatedOrderID,

        /// <remarks/>
        Username,

        /// <remarks/>
        Email,

        /// <remarks/>
        ShipAddress,

        /// <remarks/>
        BillAddress,

        /// <remarks/>
        PurchaseOrderNumber,

        /// <remarks/>
        SalesPerson,

        /// <remarks/>
        CustomerRef1,

        /// <remarks/>
        CustomerRef2,

        /// <remarks/>
        CustomerRef3,

        /// <remarks/>
        CustomerRef4,

        /// <remarks/>
        CustomerRef5,

        /// <remarks/>
        CustomerRef6,

        /// <remarks/>
        CustomerRef7,

        /// <remarks/>
        CustomerRef8,

        /// <remarks/>
        CustomerRef9,

        /// <remarks/>
        CustomerRef10,

        /// <remarks/>
        SalesChannel,

        /// <remarks/>
        GrandTotal,

        /// <remarks/>
        TaxInclusive,

        /// <remarks/>
        OrderTax,

        /// <remarks/>
        SurchargeTotal,

        /// <remarks/>
        SurchargeTaxable,

        /// <remarks/>
        ProductSubtotal,

        /// <remarks/>
        ShippingTotal,

        /// <remarks/>
        ShippingTax,

        /// <remarks/>
        ClientIPAddress,

        /// <remarks/>
        CouponCode,

        /// <remarks/>
        CouponDiscount,

        /// <remarks/>
        ShippingDiscount,

        /// <remarks/>
        OrderType,

        /// <remarks/>
        OnHoldType,

        /// <remarks/>
        OrderStatus,

        /// <remarks/>
        OrderPayment,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderPayment.PaymentType")]
        OrderPaymentPaymentType,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderPayment.DatePaid")]
        OrderPaymentDatePaid,

        /// <remarks/>
        DateUpdated,

        /// <remarks/>
        DatePlaced,

        /// <remarks/>
        DateRequired,

        /// <remarks/>
        DateInvoiced,

        /// <remarks/>
        DatePaid,

        /// <remarks/>
        DateCompleted,

        /// <remarks/>
        OrderLine,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderLine.ProductName")]
        OrderLineProductName,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderLine.ItemNotes")]
        OrderLineItemNotes,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderLine.SerialNumber")]
        OrderLineSerialNumber,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderLine.PickQuantity")]
        OrderLinePickQuantity,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderLine.BackorderQuantity")]
        OrderLineBackorderQuantity,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderLine.UnitPrice")]
        OrderLineUnitPrice,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderLine.Tax")]
        OrderLineTax,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderLine.TaxCode")]
        OrderLineTaxCode,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderLine.WarehouseID")]
        OrderLineWarehouseID,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderLine.WarehouseName")]
        OrderLineWarehouseName,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderLine.WarehouseReference")]
        OrderLineWarehouseReference,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderLine.Quantity")]
        OrderLineQuantity,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderLine.PercentDiscount")]
        OrderLinePercentDiscount,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderLine.ProductDiscount")]
        OrderLineProductDiscount,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderLine.CouponDiscount")]
        OrderLineCouponDiscount,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderLine.CostPrice")]
        OrderLineCostPrice,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderLine.ShippingMethod")]
        OrderLineShippingMethod,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderLine.ShippingTracking")]
        OrderLineShippingTracking,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderLine.Weight")]
        OrderLineWeight,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderLine.Cubic")]
        OrderLineCubic,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderLine.Extra")]
        OrderLineExtra,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderLine.ExtraOptions")]
        OrderLineExtraOptions,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderLine.BinLoc")]
        OrderLineBinLoc,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderLine.QuantityShipped")]
        OrderLineQuantityShipped,

        /// <remarks/>
        ShippingSignature,

        /// <remarks/>
        RealtimeConfirmation,

        /// <remarks/>
        InternalOrderNotes,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderLine.eBay.eBayUsername")]
        OrderLineeBayeBayUsername,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderLine.eBay.eBayStoreName")]
        OrderLineeBayeBayStoreName,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderLine.eBay.eBayTransactionID")]
        OrderLineeBayeBayTransactionID,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderLine.eBay.eBayAuctionID")]
        OrderLineeBayeBayAuctionID,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderLine.eBay.ListingType")]
        OrderLineeBayListingType,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderLine.eBay.DateCreated")]
        OrderLineeBayDateCreated,

        /// <remarks/>
        CompleteStatus,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OrderLine.eBay.DatePaid")]
        OrderLineeBayDatePaid,

        /// <remarks/>
        UserGroup,

        /// <remarks/>
        StickyNotes,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "NetoAPI")]
    public partial class GetOrderFilterUpdateResults
    {

        private GetOrderFilterUpdateResultsExportStatus exportStatusField;

        private GetOrderFilterUpdateResultsExportedToWMS exportedToWMSField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetOrderFilterUpdateResultsExportStatus ExportStatus
        {
            get
            {
                return this.exportStatusField;
            }
            set
            {
                this.exportStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetOrderFilterUpdateResultsExportedToWMS ExportedToWMS
        {
            get
            {
                return this.exportedToWMSField;
            }
            set
            {
                this.exportedToWMSField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "NetoAPI")]
    public enum GetOrderFilterUpdateResultsExportStatus
    {

        /// <remarks/>
        Pending,

        /// <remarks/>
        Exported,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "NetoAPI")]
    public enum GetOrderFilterUpdateResultsExportedToWMS
    {

        /// <remarks/>
        True,

        /// <remarks/>
        False,
    }
}